// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvqieynvadirogxmrayd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cWlleW52YWRpcm9neG1yYXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNDM5MjMsImV4cCI6MjA3MzkxOTkyM30.atD77Fg2WjWGMa_wKfFg3IxfBTNwhmi1Sl6k5LiU6Xg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});